version: '3'
services:
  web:
    image: budgeteer:1.0.9-BETA
    depends_on:
      - db
    environment:
      wichet.configurationType: PRODUCTION
      server.port: 80
      spring.datasource.url: jdbc:mysql://db:3306/budgeteer
      spring.datasource.driverClassName: com.mysql.jdbc.Driver
      spring.datasource.username: budgeteerUser
      spring.datasource.password: budgeteerPassword
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3tp4ssw0rd
      MYSQL_DATABASE: budgeteer
      MYSQL_USER: budgeteerUser
      MYSQL_PASSWORD: budgeteerPassword
